### ISSUE TITLE
Next Symfony release will break allure-php-commons

### ISSUE THREAD

**Issue by remorhaz** [allure-framework/allure-php-commons#61]
Seems that next Symfony release will break this library because `symfony/http-foundation` 5.1.0-RC1 doesn't depend on `symfony/mime` [anymore](https://github.com/symfony/http-foundation/blob/v5.1.0-RC1/composer.json), and this library still uses it's abstractions [here](https://github.com/allure-framework/allure-php-commons/blob/master/src/Yandex/Allure/Adapter/Event/AddAttachmentEvent.php).

There are two ways to solve the problem:

- Tag this library as conflicting with `symfony/http-foundation` 5.1+.
- Make new release that drops support for ancient PHP versions by requiring `symfony/mime` explicitly.

I vote for the second way. Composer will preserve legacy systems supporters from installing new versions of the library, so it won't break their tests.

The third way is a combination of both: setting conflict in a minor release and then making a major one that uses `symfony/mime` instead of `symfony/http-foundation`.

**Comment by a4blue** [comment]
Quick Fix, since it already broke my Application:
add the following to your projects composer.json:
```
"conflict": {
        "symfony/http-foundation" : "^5.0"
    }
```

**Comment by remorhaz** [comment]
I've provided the solution in #66. I propose to tag a new 1.3.0 release after (and if) it will be accepted - that will finally allow to use the library without dirty hacks in modern environments (including PHP 8.0).
