### ISSUE TITLE
Release merged commits to master

### ISSUE THREAD

**Issue by dhorienkov** [allure-framework/allure-php-commons#62]
Hello guys!
Could you please create a new release with the latest merged commits to master? It is really important for our Team. Thank you in advance!

@hostep @eroshenkoam @OndraM @just-boris @vania-pooh please help!

**Comment by baev** [comment]
1.2.0 just released

**Comment by dhorienkov** [comment]
Thank you! Could you also update the dependency in allure-framework/allure-phpunit and allure-framework/allure-behat?

**Comment by baev** [comment]
could you please provide a pull requests for that? Than I'll merge and release it ASAP
